sudo: required
language: python

services:
  - docker

install:
  - docker build -t mertongngl/flaskdemo:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mertongngl/flaskdemo:latest