sudo: required
language: python

services:
  - docker


before_install:
  - docker build -t mertongngl/flaskdemo:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master