language: python

python:
  - 3.6

dist: bionic

services:
  - docker

stages:
  - "Build & Push Docker Image"
  - "Deploy to AKS"

jobs:
  include:
    - stage: "Build & Push Docker Image"
      install: skip
      script:
        - docker build -t mertongngl/flaskdemo:$TRAVIS_BUILD_NUMBER .
        - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
          then
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
            docker push mertongngl/flaskdemo:$TRAVIS_BUILD_NUMBER;
          fi
    - stage: "Deploy to AKS"
      if: branch = master AND type != pull_request
      script:
        - az login --service-principal -u $SERVICE_PRINCIPAL_ID -p $SERVICE_PRINCIPAL_SECRET --tenant $TENANT 1> /dev/null
        - echo -e "\n\nGetting credentials for cluster--------------------\n\n"
        - az aks get-credentials --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP_NAME
        - helm init --client-only
        - if [ $(helm list | grep synapse | wc -l) == 1 ]
          then
            helm upgrade flaskdemo flask --set image.repository=mertongngl/flaskdemo:$TRAVIS_BUILD_NUMBER --set image.tag=latest --set service.name=flaskdemo --namespace travistest ;
          else
            helm install flask --name flaskdemo --set image.repository=mertongngl/flaskdemo:$TRAVIS_BUILD_NUMBER --set image.tag=latest --set service.name=flaskdemo --namespace travistest ;
          fi
        - echo -e "\n\nHelm List ------------------------\n\n"
        - helm list

install:
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - curl -L https://git.io/get_helm.sh | bash


