sudo: required
language: python

services:
  - docker

deploy:
  provider: script
  script:
    - docker build -t mertongngl/flasktest:$TRAVIS_BUILD_NUMBER .
    - docker push mertongngl/flasktest:$TRAVIS_BUILD_NUMBER